package main

// schema for JSON API response

// autogenerated from example JSON
type PlayerList []struct {
	ChampionName string `json:"championName"`
	IsBot        bool   `json:"isBot"`
	IsDead       bool   `json:"isDead"`
	Items        []struct {
		CanUse         bool   `json:"canUse"`
		Consumable     bool   `json:"consumable"`
		Count          int    `json:"count"`
		DisplayName    string `json:"displayName"`
		ItemID         int    `json:"itemID"`
		Price          int    `json:"price"`
		RawDescription string `json:"rawDescription"`
		RawDisplayName string `json:"rawDisplayName"`
		Slot           int    `json:"slot"`
	} `json:"items"`
	Level           int     `json:"level"`
	Position        string  `json:"position"`
	RawChampionName string  `json:"rawChampionName"`
	RawSkinName     string  `json:"rawSkinName"`
	RespawnTimer    float64 `json:"respawnTimer"`
	RiotID          string  `json:"riotId"`
	RiotIDGameName  string  `json:"riotIdGameName"`
	RiotIDTagLine   string  `json:"riotIdTagLine"`
	Runes           struct {
		Keystone struct {
			DisplayName    string `json:"displayName"`
			ID             int    `json:"id"`
			RawDescription string `json:"rawDescription"`
			RawDisplayName string `json:"rawDisplayName"`
		} `json:"keystone"`
		PrimaryRuneTree struct {
			DisplayName    string `json:"displayName"`
			ID             int    `json:"id"`
			RawDescription string `json:"rawDescription"`
			RawDisplayName string `json:"rawDisplayName"`
		} `json:"primaryRuneTree"`
		SecondaryRuneTree struct {
			DisplayName    string `json:"displayName"`
			ID             int    `json:"id"`
			RawDescription string `json:"rawDescription"`
			RawDisplayName string `json:"rawDisplayName"`
		} `json:"secondaryRuneTree"`
	} `json:"runes"`
	Scores struct {
		Assists    int     `json:"assists"`
		CreepScore int     `json:"creepScore"`
		Deaths     int     `json:"deaths"`
		Kills      int     `json:"kills"`
		WardScore  float64 `json:"wardScore"`
	} `json:"scores"`
	SkinID         int    `json:"skinID"`
	SkinName       string `json:"skinName"`
	SummonerName   string `json:"summonerName"`
	SummonerSpells struct {
		SummonerSpellOne struct {
			DisplayName    string `json:"displayName"`
			RawDescription string `json:"rawDescription"`
			RawDisplayName string `json:"rawDisplayName"`
		} `json:"summonerSpellOne"`
		SummonerSpellTwo struct {
			DisplayName    string `json:"displayName"`
			RawDescription string `json:"rawDescription"`
			RawDisplayName string `json:"rawDisplayName"`
		} `json:"summonerSpellTwo"`
	} `json:"summonerSpells"`
	Team string `json:"team"`
}
